import fs from 'fs';

const data = JSON.parse(fs.readFileSync('./src/data/bibleInYearPlan.json', 'utf8'));
const startIndex = 0; // index 0 in JSON is Day 1 
const endIndex = 22;  // index 22 in JSON is Day 23

console.log('| Date | Plan Day | 1st Reading | 2nd Reading | Raw JSON Citation | Rendered UI Title |');
console.log('|---|---|---|---|---|---|');

for (let i = startIndex; i <= endIndex; i++) {
    const item = data[i];
    if (!item) continue;

    let cit = item.psalm_proverbs;

    // Simulate our backend parsing logic from api/bible.js
    const match = cit.trim().match(/^(.+?)\s+(\d+)(?::(\d+)(?:-(\d+))?)?(?:-(\d+))?$/);

    let rawBook = "Unknown";
    let chapter = "1";

    if (match) {
        rawBook = match[1].trim();
        chapter = match[2];
    } else {
        rawBook = cit.split(' ')[0];
    }

    // Simulate displayBook format
    const displayBook = rawBook.split(' ').map(word => word.charAt(0).toUpperCase() + word.slice(1)).join(' ');

    // The rendered text generated by header logic in the API and stripped by the frontend
    let renderedTitle = `${displayBook} ${chapter}`;

    const dateNum = (i + 1).toString().padStart(2, '0');

    console.log(`| Feb ${dateNum} | Day ${item.day} | ${item.first_reading} | ${item.second_reading || 'None'} | ${cit} | ${renderedTitle} |`);
}
